USE [master]
GO
/****** Object:  Database [AttendeeExpo]    Script Date: 3/24/2023 8:08:02 PM ******/
CREATE DATABASE [AttendeeExpo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AttendeeExpo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AttendeeExpo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AttendeeExpo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AttendeeExpo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AttendeeExpo] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AttendeeExpo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AttendeeExpo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AttendeeExpo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AttendeeExpo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AttendeeExpo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AttendeeExpo] SET ARITHABORT OFF 
GO
ALTER DATABASE [AttendeeExpo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AttendeeExpo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AttendeeExpo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AttendeeExpo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AttendeeExpo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AttendeeExpo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AttendeeExpo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AttendeeExpo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AttendeeExpo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AttendeeExpo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AttendeeExpo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AttendeeExpo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AttendeeExpo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AttendeeExpo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AttendeeExpo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AttendeeExpo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AttendeeExpo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AttendeeExpo] SET RECOVERY FULL 
GO
ALTER DATABASE [AttendeeExpo] SET  MULTI_USER 
GO
ALTER DATABASE [AttendeeExpo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AttendeeExpo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AttendeeExpo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AttendeeExpo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AttendeeExpo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AttendeeExpo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AttendeeExpo', N'ON'
GO
ALTER DATABASE [AttendeeExpo] SET QUERY_STORE = ON
GO
ALTER DATABASE [AttendeeExpo] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AttendeeExpo]
GO
/****** Object:  Table [dbo].[Attendee]    Script Date: 3/24/2023 8:08:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Attendee](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Gender] [nchar](10) NULL,
	[Mobile] [nchar](10) NULL,
	[PostCode] [nchar](10) NULL,
	[City] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
 CONSTRAINT [PK_Attendee] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [AttendeeExpo] SET  READ_WRITE 
GO
